service: rifacafol-dev

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  apiName: rifas # Use a custom name for the API Gateway API
  memorySize: 128 # Overwrite the default memory size. Default is 1024
  timeout: 30 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
  deploymentBucket:
    name: com.serverless.us-east-1.rifacafol-dev.deploys
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:HeadObject"
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::rifa-datalake-raw-dev"
        - "arn:aws:s3:::rifa-datalake-raw-dev/*"
    - Effect: Allow
      Action:
        - "sqs:DeleteMessage"
        - "sqs:GetQueueAttributes"
        - "sqs:ReceiveMessage"
        - "sqs:SendMessage"
      Resource:
        - "arn:aws:sqs:us-east-1:113779569966:RafflePaymentSuccessDev"
        - "arn:aws:sqs:us-east-1:113779569966:RafflePaymentSuccessDevDLT"
    - Effect: Allow
      Action: "ses:SendTemplatedEmail"
      Resource: "arn:aws:ses:us-east-1:113779569966:identity/*"
  environment:
    PAYPAL_CLIENT_ID: AZx6AFHE0PdjD2a9WtPgtDwoQRdmZeKOpgBuQGaxuNVBLXsmidqJrXQ7ssccMyWO8bs5nUOsDKjwdJF-
    PAYPAL_CLIENT_SECRET: EB7WsOgv7Hvqfv4jgT37dnbO5zqwAevl216YSDPRu06GqH8AEMXG5RjSYnQWHIE_aVMVGkGQ-a1xxN43
    BUCKET_RIFA_DATALAKE_RAW: rifa-datalake-raw-dev
    SQS_QUEUE_URL_RAFFLE_PAYMENT_SUCCESS: "https://sqs.us-east-1.amazonaws.com/113779569966/RafflePaymentSuccessDev"
    SQS_QUEUE_URL_RAFFLE_PAYMENT_SUCCESS_DLT: "https://sqs.us-east-1.amazonaws.com/113779569966/RafflePaymentSuccessDevDLT"
    SES_EMAIL_SOURCE: rifacafol@gmail.com
    SES_EMAIL_TEMPLATE_SUCCESS: rifacafol-success-20201115112300
    SES_EMAIL_TEMPLATE_ERROR: rifacafol-error-20201115112300
    NODE_ENV: development

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
  raffle-processor:
    handler: index.processor
    reservedConcurrency: 1
    events:
      - sqs:
          batchSize: 1
          arn:
            Fn::GetAtt:
              - RafflePaymentSuccessDev
              - Arn

resources:
  Resources:
    RafflePaymentSuccessDev:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "RafflePaymentSuccessDev"
    RafflePaymentSuccessDevDLT:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "RafflePaymentSuccessDevDLT"